### ISSUE TITLE
Troubles with path

### ISSUE THREAD

**Issue by kud** [happyplan/happyplan#33]
@MoOx you defined:

```
"dist": {
    "path": "dist/",
    "assets": {
      "path": "<%= happyPlan.dist.path %>assets/",
      "scripts": "<%= happyPlan.dist.assets.path %>js",
      "styles": "<%= happyPlan.dist.assets.path %>css",
      "images": "<%= happyPlan.dist.assets.path %>img",
      "fonts": "<%= happyPlan.dist.assets.path %>fonts",
      "static": "<%= happyPlan.dist.assets.path %>"
    },
    "medias": "<%= happyPlan.dist.path %>medias",
    "root": "<%= happyPlan.dist.path %>"
  },
  "baseUrl": ".",
  "baseUrls": {
    "_": "<%= happyPlan.baseUrl %>/",
    "scripts": "<%= happyPlan.baseUrl %>/js",
    "styles": "<%= happyPlan.baseUrl %>/css",
    "images": "<%= happyPlan.baseUrl %>/img",
    "fonts": "<%= happyPlan.baseUrl %>/fonts",
    "medias": "<%= happyPlan.baseUrl %>/medias"
  },
```

and you use in jekyll:

```
base_urls: 
  scripts: "{{ happyPlan.baseUrls.scripts }}"
  styles: "{{ happyPlan.baseUrls.styles }}"
  images: "{{ happyPlan.baseUrls.images }}"
  fonts: "{{ happyPlan.baseUrls.fonts }}"
assets:
  main:
    style: "{{ happyPlan.assets.main.style }}"
    script: "{{ happyPlan.assets.main.script }}"
```

which means all files go to ./assets/ but you call them without /assets/, whaaaaaat?
